version: '3.8'

services:
  lista:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    container_name: appv1
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=nextdb
      - MYSQL_USER=list_user
      - MYSQL_PASSWORD=list_secret
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
  mariadb_data:
